### PR TITLE
ci: lint PR title to start subject with lowercase letter

### PR DESCRIPTION
**Pull request by alvrs**
- For consistency, we should start the PR title's subject (the part after the `feat:`/`fix:` etc prefix) with a lowercase letter
- See https://github.com/amannn/action-semantic-pull-request for context on the settings

### CODE REVIEW

**Comment by Mirror-Tang** [comment]
While maintaining consistency, it is advisable to focus more on the overall solution and propose a comprehensive standard for document editing rather than modifying a specific currently accessible link. This is more efficient.

**Comment by alvrs** [comment]
> While maintaining consistency, it is advisable to focus more on the overall solution and propose a comprehensive standard for document editing rather than modifying a specific currently accessible link. This is more efficient.

I'm not sure I can follow, can you elaborate?

**Comment by Mirror-Tang** [comment]
> > 在保持一致性的同时，建议更多地关注整体解决方案，并提出文档编辑的全面标准，而不是修改当前可访问的特定链接。这样效率更高。
> 
> 我不确定我能听懂，你能详细说明一下吗？



> > While maintaining consistency, it is advisable to focus more on the overall solution and propose a comprehensive standard for document editing rather than modifying a specific currently accessible link. This is more efficient.
> 
> I'm not sure I can follow, can you elaborate?

Apologies, English is not my native language, but I am trying to make you understand my point: the issue of case sensitivity in links is not an exception in this repository. After the document was updated yesterday, I found some incorrect hyperlinks (and I am preparing to submit them). Perhaps the official developers should introduce more detailed contribution guidelines and inspection methods to reduce errors? Or maybe perform a thorough check of the page before submitting?

**Comment by Mirror-Tang** [comment]
> > While maintaining consistency, it is advisable to focus more on the overall solution and propose a comprehensive standard for document editing rather than modifying a specific currently accessible link. This is more efficient.
> 
> I'm not sure I can follow, can you elaborate?

Apologies, English is not my native language, but I am trying to make you understand my point: the issue of case sensitivity in links is not an exception in this repository. After the document was updated yesterday, I found some incorrect hyperlinks (and I am preparing to submit them). Perhaps the official developers should introduce more detailed contribution guidelines and inspection methods to reduce errors? Or maybe perform a thorough check of the page before submitting?

**Comment by alvrs** [comment]
I think there is a misunderstanding - this PR has nothing to do with your contributions. Definitely agree we should check the correctness of links before merging PRs. This PR adds a simple lint check for the title of PRs (to lowercase the first word of the subject)

**Comment by Mirror-Tang** [comment]
> I think there is a misunderstanding - this PR has nothing to do with your contributions. Definitely agree we should check the correctness of links before merging PRs. This PR adds a simple lint check for the title of PRs (to lowercase the first word of the subject)

I suppose it was a misunderstanding on my part, thank you for clarifying.

**Pull request merged**
