### PR TITLE
chore: Integrate Turbo repo for build process, update various dependencies

### PR DESCRIPTION
**Pull request by Handfish**
Hi Lattice.

I decided to give the migration to turborepo a spin, and drafted up a locally working solution for `build`. 

Reduces initial build times and caches build hashes concerning unchanged packages to speed up subsequent builds.

### CODE REVIEW

**Comment by Handfish** [comment]
I force pushed changes over my current commit to fix some of the issues which may make this easier to test for others.

**Comment by Handfish** [comment]
I believe the present commit should pass the build and test ci/cd. 
I'm not sure what the details of the Vercel build is but I have moved the `docs` workspace to `apps/docs`.

@holic Ready for review.

**Comment by holic** [comment]
> Just want to know if this branch is of interest.

Thanks for prototyping it! Very helpful to be able to compare to our nx work.

> Seems like Nx has better performance in very large monorepos. This was an interesting experiment nonetheless.

Hard to know/say at this point. We're in the process of cleaning up a bunch of things to make our nx setup a little cleaner/clearer before merging it. Hope to have that done this week.

**Comment by roninjin10** [comment]
Awesome work!   Only had time to skim pr but I’m excited to pull branch down and try it out

**Comment by roninjin10** [comment]
Might be a good idea to rebase on top of https://github.com/latticexyz/mud/pull/633

**Comment by Handfish** [comment]
I believe this is ready-to-merge at this point. The preinstall script removed the various pnpm errors - I moved the docs folder back to it's workspace and the Vercel build seems to be working. I left the original non-turbo scripts under the `OLD-` namespace of scripts in the `package.json`. It can be cleaned up by whomever.

Just a heads up to lattice - I still am unsure of the implications of removing `private: true` from the docs `package.json`.

https://github.com/latticexyz/mud/pull/644/files#diff-adfa337ce44dc2902621da20152a048dac41878cf3716dfc4cc56d03aa212a56L13

 but it was needed for the workspace tasks or install to work.

**Comment by roninjin10** [comment]
Private true removal will tell npm to start publishing the package to npm

**Comment by Handfish** [comment]
Turns out the quotes just needed to be removed.

**Comment by Handfish** [comment]
Didn't realize mistakenly leaving and extra `../` in the `docs/package.json` command `build:prepare` path was actually what made Vercel build 🙄 - can't see the details of that failure but I put it back now and it works. Okay - sorted the root package.json - 3rd times the charm 😆

**Comment by Handfish** [comment]
This merge request is to main. #657 is a rebase to #633 as requested [above.](https://github.com/latticexyz/mud/pull/644#issuecomment-1517105608)

**Pull request closed without merging**
