### PR TITLE
fix(services): fix protobuf import

### PR DESCRIPTION
**Pull request by holic**

### CODE REVIEW

**Comment by dk1a** [comment]
check out esModuleInterop in https://github.com/stephenh/ts-proto
I'm not sure it'll fix anything, but it is likely to break something

either way, you should change the flags in makefile rather than manually edit the autogenerated stuff, and rerun `protoc-ts`

**Comment by holic** [comment]
> check out esModuleInterop in https://github.com/stephenh/ts-proto I'm not sure this PR will fix anything, but it is likely to break something
> 
> either way, you should change the flags in makefile rather than manually edit the autogenerated stuff, and rerun `protoc-ts`

Good call! I didn't realize these were auto generated. But also, seems like this workaround is ~common 😭 

https://github.com/stephenh/ts-proto/issues/536#issuecomment-1198154550

**Comment by alvrs** [comment]
Maybe we could add a script to automatically replace those lines until it's fixed in `ts-proto`?

**Comment by dk1a** [comment]
why the star import may be bad:
https://github.com/stephenh/ts-proto/issues/738
https://github.com/vitejs/vite/issues/9018#issuecomment-1179728774

the issue seems to be a macos thing, my guess something to do with tsconfig

**Comment by holic** [comment]
> the issue seems to be a macos thing, my guess something to do with tsconfig

when you say "macos thing", do we think it's an issue at build time? so every browser would see this if the client is built on macos?

**Pull request closed without merging**
