### PR TITLE
increasing node memory to be able to build the store-sync package

### LINKED ISSUE #2801: [bug] unable to build historical indexer
Hi,

I'm trying to build the docker image from the historical indexer branch, but it fails. The error message is:

```
193.5 packages/store-sync build: node:events:495
193.5 packages/store-sync build:       throw er; // Unhandled 'error' event
193.5 packages/store-sync build:       ^
193.5 packages/store-sync build: Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
193.5 packages/store-sync build:     at new NodeError (node:internal/errors:405:5)
193.5 packages/store-sync build:     at [kOnExit] (node:internal/worker:301:26)
193.5 packages/store-sync build:     at Worker.<computed>.onexit (node:internal/worker:222:20)
193.5 packages/store-sync build: Emitted 'error' event on Worker instance at:
193.5 packages/store-sync build:     at [kOnExit] (node:internal/worker:301:12)
193.5 packages/store-sync build:     at Worker.<computed>.onexit (node:internal/worker:222:20) {
193.5 packages/store-sync build:   code: 'ERR_WORKER_OUT_OF_MEMORY'
193.5 packages/store-sync build: }
193.5 packages/store-sync build: Node.js v18.20.2
193.6 packages/store-sync build:  ELIFECYCLE  Command failed with exit code 1.
193.6 packages/store-sync build: Failed
193.6 /app/packages/store-sync:
193.6  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @latticexyz/store-sync@2.0.4 build: `pnpm run build:js`
193.6 Exit status 1
```

It seems like the node process in the docker image doesn't have enough memory to build the store-sync package. To solve this, the memory limit within docker needs to be changed. I will open a PR to solve this.

### PR DESCRIPTION
**Pull request by joergkiesewetter**
fixes #2801

### CODE REVIEW

**Review by holic — APPROVED** [review]
this nicely mirrors https://github.com/latticexyz/mud/blob/0ae9189ca60e86f7b12994bcc89bc196871d0e7c/.github/workflows/build.yml#L9-L10 from https://github.com/latticexyz/mud/pull/2772

**Comment by holic** [comment]
I just noticed this is running on an old fork of this repo with some changes that diverge from main. Mind rebasing your branch on latest main?

**Comment by joergkiesewetter** [comment]
This PR is targeting branch 'historical_indexer', because I need the change in this branch. Should I make a new one for main branch and you merge main into historical_indexer?

**Comment by holic** [comment]
oh sorry! I missed that detail in the description in the issue

what are you using the historical indexer for? that'd help me figure out if we should catch it up to main or not

**Comment by holic** [comment]
this would be a welcome change in main as well if you're up for it!

**Comment by joergkiesewetter** [comment]
> oh sorry! I missed that detail in the description in the issue
> 
> what are you using the historical indexer for? that'd help me figure out if we should catch it up to main or not

it's used for the skystrife analytics dashboard by world explorers https://skystrife.worlds.online/

**Comment by joergkiesewetter** [comment]
I created a new pull request for main #2810

**Pull request merged**
