### PR TITLE
fix(common): include only errors defined in the contract

### PR DESCRIPTION
**Pull request by dk1a**
pulled out of #2171

### CODE REVIEW

**Review by holic — DISMISSED** [review]
Is there some way to show the outcome of this? In a test or in some example codegen interface?

**Comment by dk1a** [comment]
> Is there some way to show the outcome of this? In a test or in some example codegen interface?

Yeah, we never ran into the issue but I can make an example, test would be trickier (btw do we have tests that compare solidity file contents to expected output?)

**Comment by holic** [comment]
> btw do we have tests that compare solidity file contents to expected output?

not really but a snapshot test would be fine for this I think (grep for `toMatchInlineSnapshot`)! I am fine with either that or an example that shows output

**Comment by dk1a** [comment]
Added a simple example (it incorrectly generates the error in main branch)

**Review by holic — APPROVED** [review]

**Pull request merged**
