### PR TITLE
feat(templates): integrate external wallet into React template

### LINKED ISSUE #2260: Support for external wallets in templates
- This issue is part of https://github.com/latticexyz/mud/issues/2256

# Motivation

Currently, the templates generated by the `create-mud` command use internal burner wallets in the clients. To facilitate non-local environments, developers are required to manually integrate external wallet connections.

Having external wallet support into the templates would be beneficial. This issue is aimed at achieving that goal.

# Possible implementation options

Several approaches can be considered.

## External wallet support options

Note: `wagmi` is a React library that internally utilizes the vanilla JavaScript library `@wagmi/core`.

Major libraries supporting wallet connections include:

- [`@rainbow-me/rainbowkit`](https://www.rainbowkit.com/): Styled React components built on `wagmi`. Used by Sky Strife and Redstone websites.
- [`connectkit`](https://docs.family.co/connectkit): Styled React components built on `wagmi`.
- [`@rabby-wallet/rabbykit`](https://rabbykit.rabby.io/): Styled UI built on `@wagmi/core`.
- [`@web3modal/wagmi`](https://docs.walletconnect.com/web3modal/about): Styled UI built on `@wagmi/core`.
- [`wagmi`](https://wagmi.sh/react/guides/connect-wallet#build-your-own): React Hooks built on `@wagmi/core`.
- [`@wagmi/core` (and `@wagmi/connectors`)](https://wagmi.sh/core/api/connectors): A vanilla JavaScript library.
- [`mipd`](https://github.com/wevm/mipd): JavaScript utilities for [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) by the wevm team. This is used in `@wagmi/core`. The retrieved Ethereum providers can be used for [the `viem`'s client custom transport](https://viem.sh/docs/clients/wallet#json-rpc-accounts). Although the conventional `window.ethereum` ([EIP-1193](https://eips.ethereum.org/EIPS/eip-1193)) still works with viem, it's not recommended due to limitations in multi-wallet support. Most wallets are [compatible](https://github.com/WalletConnect/EIP6963/blob/4754abdef8a30ceb74d1126e131fee2e08dbd611/src/utils/constants.ts) with EIP-6963.

## Options for integrating external wallets into templates

The objective is to maintain the current user experience in existing templates, which are designed to work out-of-the-box without necessitating external wallets.

Options include:

- Creating new templates that use external wallets instead of the existing burner wallets.
- Updating existing templates to support both external wallets and burner wallets.

Ideally, the `create-mud` command would allow users to choose their preferences for various aspects (e.g., react or vanilla, burner or external wallet, wagmi or rainbowkit, ecs or something). However, this requires improvement to template management and `create-mud`, which I'd like to work on a separate project if desired.

# Proposed solution

For the external wallet connection, I'd like to use `@wagmi/core` for vanilla templates and `wagmi` for react templates. This approach is preferred as it's less-opinionated and does not add any new dependencies, since developers are likely to use Wagmi in their projects. I will not include support for [the WalletConnect v2 protocol](https://specs.walletconnect.com/2.0/specs/clients/sign/), as it requires a project ID for setup. Developers can [add the support later](https://wagmi.sh/core/api/connectors/walletConnect) easily.

For the integration of external wallet support into templates, I'd like to create new templates (`vanilla-external-wallet` and `react-external-wallet`) that include this feature, thereby not impacting existing templates. As the better wallet support project advances, I plan to update these new templates continually. Once it's ready, I'll apply the wallet support into the existing templates and remove the newly added ones. An alternative approach could be starting with implementations in the `examples/` directory before rolling them out to the templates. I don't think combining the existing burner wallets and external wallets within the same client is a good idea due to the complexity it introduces. Wagmi does not effectively manage providers and burner wallets together, so the client code would need additional wallet management logic.

### PR DESCRIPTION
**Pull request by tash-2s**
## Summary

This pull request introduces the ability to use external wallets with the React template. In addition to the existing standalone burner account option, users can now opt for external wallets in the client UI. Regardless of whether they choose the standalone burner account setup or the external wallet with a delegated burner account setup, they can use the app without feeling any difference.

This PR aims to allow developers to integrate external wallets easily, which is necessary for non-development chains. It also maintains the standalone burner account experience to avoid the frictions of using external wallets during local development.

## Experience

After the client is launched, users first choose between a standalone burner account and an external wallet with a delegated burner account. Selecting the former allows immediate use of the app, while the latter guides users to connect their external wallets and register delegation to their burner accounts. Afterward, they can start using the app.

When editing `App.ts` and `createSystemCalls.ts`, there's no need to account for these differences because the code manages them under the hood.

## Structure

Below is the structure of the React components:

https://github.com/latticexyz/mud/blob/af147bbcbc4cdb2b151def434bb10df5344c58b3/templates/react/packages/client/src/index.tsx#L16-L26

To explain this, here is the expanded version with comments:

```tsx
// Configures Wagmi. Wagmi is only used for an external wallet.
// Rerendering of this component is not allowed. So, it is placed at the root level.
// (We cannot mount at the point when an external wallet is selected.)
<WagmiProvider config={wagmiConfig}>

  // Wagmi depends on QueryClient.
  <QueryClientProvider client={queryClient}>

    // Holds an immutable network config (e.g., World address, public client, client store),
    // which is the result of `setupNetwork()`.
    <NetworkProvider network={network}>

      // Waits for the client store's sync before rendering its children.
      // Until then, displays a progress message.
      <StoreSync>

        // Manages wallets. This does not block its children's rendering.
        // This comes after `StoreSync` because this may use the delegation table.
        //
        // Can be in one of three states: unset, external-with-delegated-burner, and standalone-burner.
        //
        // - unset: An initial state. Allows a user to select either external-with-delegated-burner or standalone-burner.
        // - external-with-delegated-burner: Allows a user to connect an external wallet and then
        //   register delegation between the external account and a burner account.
        // - standalone-burner: Uses a burner account without an external wallet.
        //   No additional user interaction is involved. This is only available when in development mode.
        <WalletManager>

          // Holds `burner` that includes a wallet client and a World contract.
          // `burner` is null until the delegated burner is ready or the standalone-burner is selected.
          // The burner account is not created during `setupNetwork()`. Instead, it's created when necessary.
          <BurnerProvider burner={burner}>

            // The main component that users face.
            // When the burner is not available, this works in a read-only mode.
            <App>
              /*
               * E.g.,
               * ```
               * const {
               *   network: { tables, useStore },
               *   burner, // type: Burner | undefined
               * } = useMUD(); // Internally, this utilizes `NetworkContext`, `BurnerContext`, and `createSystemCalls.ts`.
               * ```
               * - `burner?.systemCalls.addTask("something")`
               * - `burner?.walletClient`
               * - `burner?.worldContract`
               */

            // Displays dev-tools for a burner account when in development mode.
            {import.meta.env.DEV && <DevTools />}
```

## Demo

https://github.com/latticexyz/mud/assets/81064017/6f3e0a35-6a13-4da3-a3dd-f415b25e1e19

## Misc.

This PR includes the same code as #2366. Once the PR is merged, `callFrom.ts` and its associated dependencies (`protocol-parser` and `store`) can be removed.

- Closes #2260
	- I changed the approach from the one mentioned in this issue since I realized we should keep the existing standalone burner setup for developer experience.
- Closes #2306
- Closes #2307
- Closes #2309

### CODE REVIEW

**Comment by tash-2s** [comment]
The branch handling got disorganized. I'll make sure to manage it better next time. 😵‍💫

**Comment by tash-2s** [comment]
This PR is ready for review. I've addressed the previous feedback, organized the structure, and added comments.

@holic I'd appreciate your feedback on this when you're available. I can update the approach and code as needed. Also, please point out anything that may be difficult to understand or requires further explanation. 🙇

**Comment by tash-2s** [comment]
The CI failed because turbo used the main branch's build cache and did "cache hit" for packages changed on main for some reason. 🤔 I'll merge main at some point.

**Comment by tash-2s** [comment]
I've removed `callFrom` since it was merged in #2366. Also, I've added a short README containing instructions for using external wallets.

**Comment by holic** [comment]
closing as we're taking a different approach for onboarding

**Pull request closed without merging**
