### PR TITLE
refactor(world): extcodesize not needed in Create2 library [n-08]

### PR DESCRIPTION
**Pull request by yonadaaa**

### CODE REVIEW

**Comment by holic** [comment]
Do we have gas coverage to know if this changes gas?

And if there are side effects in terms of gas, I almost prefer the current approach with `extcodesize` as it reads a bit clearer to me.

**Comment by yonadaaa** [comment]
> Do we have gas coverage to know if this changes gas?

It doesn't seem like it. I'll check which codepath uses this and add some.

> I almost prefer the current approach with extcodesize as it reads a bit clearer to me.

If we remove the opcode we should add a comment because it requires somewhat contextual knowledge - that the address will be zero in this case.

**Comment by holic** [comment]
Oh I see, the logic is changing from "check if the resulting contract address exists/has bytecode" into "check if the resulting contract address is address zero"?

**Comment by yonadaaa** [comment]
Exactly, if the call was successful the address should be _something_ (not zero), and the bytecode will be non-empty too. I don't think you have one without the other. 

I'm not sure why the `create2` call doesn't just revert. I guess it's low-level and allows the caller to handle the error.

**Review by holic — APPROVED** [review]

**Pull request merged**
