### PR TITLE
docs: fix git clone command

### PR DESCRIPTION
**Pull request by qbzzt**
It doesn't work as `git clone git@github.com`, it works as `git clone github.com`

### CODE REVIEW

**Comment by holic** [comment]
Thank you! Out of curiosity, what OS and terminal are you using to git clone where it didn't work?

**Comment by qbzzt** [comment]
> what OS and terminal are you using to git clone where it didn't work?

Linux development system on a Chromebook.

```
qbzzt1@penguin:~/mud/erc20/packages/contracts/src/systems$ uname -a
Linux penguin 5.15.108-18910-gab0e1cb584e1 #1 SMP PREEMPT Sat Jun 3 18:21:02 PDT 2023 x86_64 GNU/Linux
qbzzt1@penguin:~/mud/erc20/packages/contracts/src/systems$ echo $SHELL
/bin/bash
```

> They both work, but git@github.com:latticexyz/emojimon.git is over ssh so you need to setup a key

Is there anything github that requires ssh rather than https?

**Comment by dk1a** [comment]
> Is there anything github that requires ssh rather than https?

Last I tried https could only pull, not push. For emojimon that's not much of a problem

**Comment by qbzzt** [comment]
If you use the url `https://<token>:x-oauth-basic@github.com/owner/repo.git` you can also push.

**Pull request merged**
