### PR TITLE
feat(cli): add a RPC batch option to cli

### PR DESCRIPTION
**Pull request by hourglasshoro**
This PR adds a RPC batch size option to the deploy command.

Resolve: https://github.com/latticexyz/mud/issues/2236

### CODE REVIEW

**Comment by hourglasshoro** [comment]
@holic 

> https://github.com/latticexyz/mud/issues/2236#issuecomment-1929947276

There was no corresponding throttling, but there was one that did batch processing instead, so this was substituted. 
https://viem.sh/docs/clients/transports/http#batch-json-rpc

In my environment, setting batchSize to 1000 allowed me to deploy without any errors.

I have closed PRs I made in the past and made new ones
https://github.com/latticexyz/mud/pull/2322

**Comment by holic** [comment]
Out of curiosity, does `batch: true` do the same thing for you?

**Comment by hourglasshoro** [comment]
I don't think just `batch:true` will work, because if you don't specify `batch.wait`, the batch control will not work for 1 second(default wait 0 second).
https://viem.sh/docs/clients/transports/http#batchwait-optional

**Comment by hourglasshoro** [comment]
Do you usually update the document side with the same PR?

**Comment by holic** [comment]
If you read further up, it'll still batch within the same "tick" (see also [zero delay](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop#zero_delays)):

image

This makes me suspect most of our operations would be batched because they're often sent simultaneously.

**Comment by holic** [comment]
> Do you usually update the document side with the same PR?

Yep!

**Comment by hourglasshoro** [comment]
The same effect as throttling could only be achieved if a sufficiently large batchSize and a sufficiently long wait were set

My hypothesis is this.
For example, each `ensureHoge` calls `Promise.all` internally, and `Promise.all` does multiple etc_calls in one step
https://github.com/latticexyz/mud/blob/main/packages/cli/src/deploy/deploy.ts#L93-L114

1) If batchSize is small, more batches are split, more requests are sent per second, and quote is limited.
2) If the wait time is short, requests are sent at short intervals even if batchSize is large, and quote is limited.

I am not sure what should be taken as the argument of cli

**Comment by hourglasshoro** [comment]
I'm guessing based on the actual results I've tried, so I could be wrong.

**Comment by hourglasshoro** [comment]
Of course, I've tried `batch: true` and still hit RPC rate limits

Since batchSize and wait are defaults when batchTrue, respectively
batchSize: [1000](https://viem.sh/docs/clients/transports/http#batchbatchsize-optional), wait: [0(ms)](https://viem.sh/docs/clients/transports/http#batchwait-optional)

My environment is this. 
- 1 system
- 20 tables
- 1 module
- RPC Endpoint: Alchemy Growth Plan (https://www.alchemy.com/pricing)
---

Here are the results of the search with each parameter fixed
- batchSize: 10, wait: 1000(ms): hit RPC rate limits
- batchSize: 100, wait: 1000(ms): no error
- batchSize: 100, wait: 0(ms): hit RPC rate limits
- batchSize: 100, wait: 10(ms): hit RPC rate limits
- batchSize: 100, wait: 100(ms): hit RPC rate limits

**Comment by holic** [comment]
asked if we could enable this by default but sounds like there's no good way to detect if batching is supported so keeping it as an option makes sense: https://discord.com/channels/1156791276818157609/1212120089219043369

**Review by holic — APPROVED** [review]

**Pull request merged**
