### PR TITLE
feat(network): don't filter historical ephemeral events

### PR DESCRIPTION
**Pull request by smallbraingames**
- can always filter later, but can't unfilter

### CODE REVIEW

**Comment by smallbraingames** [comment]
If this is approved before 8/6 I will be mega happy bc launch coming up soon <3

But if not that's also ok

**Review by holic — APPROVED** [review]
I'm fine with this but wanna make sure this is compatible with Sky Strife and they have a good workaround.

**Comment by alvrs** [comment]
reminder to add a changeset describing this change

**Comment by alvrs** [comment]
I wonder if this change is still necessary since it's a change to the v1 network stack that will be removed _very soon_ and the v2 stack already syncs ephemeral table events?

**Comment by smallbraingames** [comment]
> I wonder if this change is still necessary since it's a change to the v1 network stack that will be removed _very soon_ and the v2 stack already syncs ephemeral table events?

Yeah true, I don't need it anymore since I'm on new network stack (should have updated here, ty for reminder)

**Comment by holic** [comment]
might be nice to merge for consistency between v1 and v2 though since this'll be the default in v2

**Pull request merged**
