### PR TITLE
feat(cli): mud pull

### PR DESCRIPTION
**Pull request by holic**

### CODE REVIEW

**Review by alvrs — APPROVED** [review]
lgtm! note: just tried it out on a base chain and ran into a `eth_getLogs is limited to a 10,000 range` error

**Comment by alvrs** [comment]
> just tried it out on a base chain and ran into a eth_getLogs is limited to a 10,000 range error

should this be fixed by https://github.com/latticexyz/mud/pull/3217?

**Comment by holic** [comment]
> > just tried it out on a base chain and ran into a eth_getLogs is limited to a 10,000 range error
> 
> should this be fixed by #3217?

It's fixed for fetching the world deploy, but still needs work for e.g. getting resource IDs.

**Comment by holic** [comment]
Okay you nerd sniped me: https://github.com/latticexyz/mud/pull/3245

**Review by alvrs — APPROVED** [review]

**Pull request merged**
